export enum ActionType {
  SET_CHOSEN_TOOL = "SET_CHOSEN_TOOL",
  MOVE_PLAYER_TOOL = "MOVE_PLAYER_TOOL",
  MOVE_AND_KILL_PLAYER_TOOL = "MOVE_AND_KILL_PLAYER_TOOL",
  SET_OPTIONS_AND_GAME_STATE = "SET_OPTIONS_AND_GAME_STATE",
  SWITCH_PLAYER_TURN = "SWITCH_PLAYER_TURN",
  MOVE_EN_PASSANT_PLAYER_TOOL = "MOVE_EN_PASSANT_PLAYER_TOOL",
}
